import type { Metadata } from "next";
import { satoshi, generalSans, specialElite } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "ShhhType — Speak It. Publish It. | Voice to LinkedIn Content",
  description:
    "ShhhType turns your voice into ready-to-publish LinkedIn posts, DMs, and connection notes with a single spoken command. What used to take 30 minutes now takes 60 seconds. Available on macOS and Windows.",
  keywords:
    "voice to LinkedIn, LinkedIn content creator, LinkedIn post generator, voice to content, speech to text, LinkedIn DM, LinkedIn connection note, AI LinkedIn writer, voice skills, voice-to-content, macOS, Windows, voice typing, content creation",
  metadataBase: new URL("https://shhhtype.com"),
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: "https://shhhtype.com/",
    title: "ShhhType — Speak It. Publish It.",
    description:
      "What used to take 30 minutes now takes 60 seconds. Speak your ideas, say /linkedin, and get a formatted post with bold text, hooks, and hashtags. Your voice, structured by AI — not generated by it.",
    siteName: "ShhhType",
    images: [
      {
        url: "/images/og-image.png",
        width: 1200,
        height: 630,
        alt: "ShhhType — Speak It. Publish It.",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "ShhhType — Speak It. Publish It.",
    description:
      "What used to take 30 minutes now takes 60 seconds. Voice-to-content for LinkedIn creators and sales pros.",
    images: ["/images/og-image.png"],
  },
  icons: {
    icon: "/images/shhh_logo_thick.png",
    apple: "/images/shhh_logo_thick.png",
  },
  other: {
    "theme-color": "#f43f5e",
    "apple-mobile-web-app-title": "ShhhType",
    "application-name": "ShhhType",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth overflow-x-hidden">
      <body
        className={`${satoshi.variable} ${generalSans.variable} ${specialElite.variable} bg-[#EBEBEB] text-gray-900 font-body antialiased overflow-x-hidden flex flex-col min-h-screen w-full max-w-[100vw]`}
      >
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "SoftwareApplication",
              name: "ShhhType",
              description:
                "Voice-to-content tool for macOS and Windows. Speak your ideas, say /linkedin, and get a ready-to-publish post in 60 seconds. Voice-triggered skills handle LinkedIn posts, DMs, and connection notes.",
              url: "https://shhhtype.com",
              applicationCategory: "UtilitiesApplication",
              operatingSystem: "macOS, Windows",
              offers: {
                "@type": "Offer",
                price: "20.00",
                priceCurrency: "USD",
                availability: "https://schema.org/InStock",
              },
              featureList:
                "Voice Skills, LinkedIn post creation, LinkedIn DM generation, Connection notes, AI rewrite, Voice to text, Global hotkey, Local Whisper transcription, Cloud Groq transcription, 9 language support, Menu bar and system tray app, macOS, Windows",
              softwareVersion: "1.0",
              downloadUrl:
                "https://shhhtype.lemonsqueezy.com/checkout/buy/c74816d2-4704-4248-abcb-fe565d518935",
              author: {
                "@type": "Organization",
                name: "Genesis1 Tech",
                url: "https://g1tech.cloud",
              },
            }),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "FAQPage",
              mainEntity: [
                {
                  "@type": "Question",
                  name: "How does ShhhType work?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "Hold your hotkey, speak your idea for 30 seconds, and say /linkedin. ShhhType transcribes your voice and structures it into a ready-to-publish LinkedIn post with hooks, bold text, spacing, and hashtags. The whole process takes about 60 seconds — what used to take 30 minutes.",
                  },
                },
                {
                  "@type": "Question",
                  name: "What are Voice Skills?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "Voice Skills are voice-triggered commands that structure your speech into specific content formats. Say /linkedin to create a formatted post with hooks, bold text, and hashtags. Say /dm for personalized LinkedIn DMs under 300 characters. Say /connect for connection notes within LinkedIn's 200-character limit. You can also build your own custom skills with simple .md files — no code required.",
                  },
                },
                {
                  "@type": "Question",
                  name: "Does ShhhType work offline?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "Yes. ShhhType supports local transcription using Whisper running directly on your machine with GPU acceleration (Metal on macOS, DirectML on Windows). No internet connection required for basic transcription.",
                  },
                },
                {
                  "@type": "Question",
                  name: "How much does ShhhType cost?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "ShhhType offers a 7-day free trial. After the trial, plans start at $20/month or $200/year. All features are included — Voice Skills, AI Rewrite, LinkedIn formatting, 9 languages, and more.",
                  },
                },
                {
                  "@type": "Question",
                  name: "What languages does ShhhType support?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "ShhhType supports 9 languages including English, Spanish, French, German, Italian, Portuguese, Dutch, Japanese, and Chinese. You can create LinkedIn content in any supported language.",
                  },
                },
              ],
            }),
          }}
        />
        {children}
      </body>
    </html>
  );
}
