export function PrivacyContent() {
  return (
    <div>
      <h1 className="text-3xl sm:text-4xl font-montserrat font-semibold text-gray-900 tracking-tight mb-2">
        Privacy Policy
      </h1>
      <p className="text-sm text-gray-400 font-montserrat mb-8">
        <strong>Effective Date:</strong> March 25, 2026 &nbsp;|&nbsp;{" "}
        <strong>Last Updated:</strong> March 25, 2026
      </p>

      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        Genesis 1 Technologies, LLC (&ldquo;Company&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;,
        &ldquo;our&rdquo;) operates ShhhType (&ldquo;the App&rdquo;), a voice-to-text desktop
        application. This Privacy Policy describes how we collect, use, disclose, and protect your
        information when you use the App.
      </p>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        By using ShhhType, you consent to the practices described in this Privacy Policy.
      </p>

      <h2 className="text-xl sm:text-2xl font-montserrat font-semibold text-gray-900 mt-10 mb-4 tracking-tight">
        1. Information We Collect
      </h2>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        1.1 Information You Provide
      </h3>
      <ul className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4 ml-6 list-disc">
        <li className="mb-2">
          <strong>Account and License Information:</strong> When you purchase a subscription, we
          collect your email address and payment information through our payment processor,
          LemonSqueezy. We do not directly store your payment card details.
        </li>
        <li className="mb-2">
          <strong>Email for Communications:</strong> If you opt in, we collect your email address to
          send you product updates, tips, and promotional communications.
        </li>
        <li className="mb-2">
          <strong>Support Requests:</strong> If you contact us at{" "}
          <a
            href="mailto:help@shhhtype.com"
            className="text-rose-600 hover:text-rose-700 underline"
          >
            help@shhhtype.com
          </a>
          , we collect the information you include in your message.
        </li>
      </ul>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        1.2 Information Generated by the App
      </h3>
      <ul className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4 ml-6 list-disc">
        <li className="mb-2">
          <strong>Audio Recordings:</strong> When you use ShhhType, the App captures audio from your
          microphone for the sole purpose of transcription. Audio is processed in real time and is{" "}
          <strong>not stored permanently</strong>. See Section 2 for details on how audio is
          handled.
        </li>
        <li className="mb-2">
          <strong>Transcription Text:</strong> Transcribed text is stored locally on your device in
          a SQLite database for your personal history. This data never leaves your device unless you
          choose to use cloud transcription.
        </li>
        <li className="mb-2">
          <strong>Machine Identifier:</strong> A hashed version of your macOS hardware UUID is
          generated locally to activate and validate your software license. This identifier cannot
          be used to determine your actual hardware UUID.
        </li>
        <li className="mb-2">
          <strong>Application Settings:</strong> Your preferences (hotkey configuration,
          transcription backend choice, overlay position, rewrite style, dictionary entries) are
          stored locally on your device.
        </li>
      </ul>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        1.3 Information We Do Not Collect
      </h3>
      <ul className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4 ml-6 list-disc">
        <li className="mb-2">
          We do <strong>not</strong> collect analytics or telemetry data.
        </li>
        <li className="mb-2">
          We do <strong>not</strong> track your usage patterns, keystrokes, or browsing activity.
        </li>
        <li className="mb-2">
          We do <strong>not</strong> access or store the content you dictate beyond what is kept in
          your local transcription history.
        </li>
        <li className="mb-2">
          We do <strong>not</strong> use cookies or similar tracking technologies (the App is a
          native desktop application).
        </li>
      </ul>

      <h2 className="text-xl sm:text-2xl font-montserrat font-semibold text-gray-900 mt-10 mb-4 tracking-tight">
        2. How Audio Data Is Handled
      </h2>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        ShhhType offers two transcription modes. How your audio is processed depends on which mode
        you select:
      </p>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        2.1 Local Transcription (Default)
      </h3>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        Audio is processed entirely on your device using a locally downloaded Whisper AI model with
        Metal GPU acceleration. <strong>No audio data leaves your device.</strong> The audio buffer
        is discarded immediately after transcription is complete.
      </p>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        2.2 Cloud Transcription (Groq API)
      </h3>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        If you enable cloud transcription, your audio is:
      </p>
      <ol className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4 ml-6 list-decimal">
        <li className="mb-2">Captured locally and encoded as a 16-bit WAV file;</li>
        <li className="mb-2">
          Transmitted over an encrypted HTTPS connection directly from your device to Groq&apos;s
          API servers;
        </li>
        <li className="mb-2">
          Processed by Groq for transcription and then discarded &mdash; Groq does not retain your
          audio data for model training per their API terms.
        </li>
      </ol>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        <strong>
          We do not receive, intercept, or store your audio at any point.
        </strong>{" "}
        The audio is sent directly from your device to Groq. We have no servers that process or
        relay your audio data.
      </p>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        For details on how Groq handles data, please refer to{" "}
        <a
          href="https://groq.com/privacy-policy/"
          className="text-rose-600 hover:text-rose-700 underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          Groq&apos;s Privacy Policy
        </a>
        .
      </p>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        2.3 AI Rewrite Feature
      </h3>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        If you use the AI rewrite feature, your transcribed text (not audio) is sent to Groq&apos;s
        API for processing by a large language model. The same data handling principles apply
        &mdash; the text is sent directly from your device to Groq and is not retained by Groq for
        training purposes.
      </p>

      <h2 className="text-xl sm:text-2xl font-montserrat font-semibold text-gray-900 mt-10 mb-4 tracking-tight">
        3. How We Use Your Information
      </h2>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        We use the information we collect for the following purposes:
      </p>
      <table className="w-full text-sm text-left mb-6 border-collapse">
        <thead>
          <tr className="border-b border-gray-200">
            <th className="text-xs font-montserrat font-bold text-gray-500 uppercase tracking-wider pb-3 pr-4">
              Information
            </th>
            <th className="text-xs font-montserrat font-bold text-gray-500 uppercase tracking-wider pb-3 pr-4">
              Purpose
            </th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-b border-gray-200">
            <td className="py-3 pr-4 text-gray-600 font-montserrat">Email address</td>
            <td className="py-3 pr-4 text-gray-600 font-montserrat">
              License delivery, subscription management, product updates and promotional emails
              (opt-in only)
            </td>
          </tr>
          <tr className="border-b border-gray-200">
            <td className="py-3 pr-4 text-gray-600 font-montserrat">Payment information</td>
            <td className="py-3 pr-4 text-gray-600 font-montserrat">
              Subscription billing (processed by LemonSqueezy)
            </td>
          </tr>
          <tr className="border-b border-gray-200">
            <td className="py-3 pr-4 text-gray-600 font-montserrat">
              Machine identifier (hashed)
            </td>
            <td className="py-3 pr-4 text-gray-600 font-montserrat">
              License activation and validation
            </td>
          </tr>
          <tr className="border-b border-gray-200">
            <td className="py-3 pr-4 text-gray-600 font-montserrat">Audio data</td>
            <td className="py-3 pr-4 text-gray-600 font-montserrat">
              Real-time transcription (local or via Groq)
            </td>
          </tr>
          <tr className="border-b border-gray-200">
            <td className="py-3 pr-4 text-gray-600 font-montserrat">Transcription text</td>
            <td className="py-3 pr-4 text-gray-600 font-montserrat">
              Local history stored on your device
            </td>
          </tr>
          <tr className="border-b border-gray-200">
            <td className="py-3 pr-4 text-gray-600 font-montserrat">Support correspondence</td>
            <td className="py-3 pr-4 text-gray-600 font-montserrat">
              Responding to your inquiries
            </td>
          </tr>
        </tbody>
      </table>

      <h2 className="text-xl sm:text-2xl font-montserrat font-semibold text-gray-900 mt-10 mb-4 tracking-tight">
        4. Information Sharing and Disclosure
      </h2>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        We do not sell, rent, or trade your personal information. We share information only in the
        following limited circumstances:
      </p>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        4.1 Third-Party Service Providers
      </h3>
      <table className="w-full text-sm text-left mb-6 border-collapse">
        <thead>
          <tr className="border-b border-gray-200">
            <th className="text-xs font-montserrat font-bold text-gray-500 uppercase tracking-wider pb-3 pr-4">
              Provider
            </th>
            <th className="text-xs font-montserrat font-bold text-gray-500 uppercase tracking-wider pb-3 pr-4">
              Data Shared
            </th>
            <th className="text-xs font-montserrat font-bold text-gray-500 uppercase tracking-wider pb-3 pr-4">
              Purpose
            </th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-b border-gray-200">
            <td className="py-3 pr-4 text-gray-600 font-montserrat">
              <strong>LemonSqueezy</strong>
            </td>
            <td className="py-3 pr-4 text-gray-600 font-montserrat">
              Email, payment info, hashed machine ID
            </td>
            <td className="py-3 pr-4 text-gray-600 font-montserrat">
              Payment processing, license management
            </td>
          </tr>
          <tr className="border-b border-gray-200">
            <td className="py-3 pr-4 text-gray-600 font-montserrat">
              <strong>Groq</strong>
            </td>
            <td className="py-3 pr-4 text-gray-600 font-montserrat">
              Audio data (cloud mode), transcription text (rewrite feature)
            </td>
            <td className="py-3 pr-4 text-gray-600 font-montserrat">
              Speech-to-text transcription, AI text rewriting
            </td>
          </tr>
        </tbody>
      </table>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        These providers process data under their own privacy policies and terms of service.
      </p>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        4.2 Legal Requirements
      </h3>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        We may disclose your information if required to do so by law or in response to valid
        requests by public authorities (e.g., a court order or government agency).
      </p>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        4.3 Business Transfers
      </h3>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        In the event of a merger, acquisition, or sale of assets, your information may be
        transferred as part of that transaction. We will notify you of any such change via email or
        a prominent notice in the App.
      </p>

      <h2 className="text-xl sm:text-2xl font-montserrat font-semibold text-gray-900 mt-10 mb-4 tracking-tight">
        5. Data Storage and Security
      </h2>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        5.1 Local Storage
      </h3>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        The majority of your data is stored locally on your macOS device at:
      </p>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded font-mono">
          ~/Library/Application Support/com.g1tech.shhhtype/
        </code>
      </p>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        This includes your settings, transcription history, dictionary, and downloaded AI models.
        This data is protected by your macOS user account permissions and any disk encryption you
        have enabled (e.g., FileVault).
      </p>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        5.2 Security Measures
      </h3>
      <ul className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4 ml-6 list-disc">
        <li className="mb-2">All network communications use HTTPS/TLS encryption.</li>
        <li className="mb-2">
          Your machine identifier is a one-way hash that cannot be reversed to obtain your hardware
          UUID.
        </li>
        <li className="mb-2">
          We do not operate servers that store your personal data (except email addresses for
          communications).
        </li>
        <li className="mb-2">
          Audio data is held in memory only during active transcription and is discarded immediately
          after processing.
        </li>
      </ul>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        5.3 Data We Store
      </h3>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        The only personal data we store on our systems is:
      </p>
      <ul className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4 ml-6 list-disc">
        <li className="mb-2">
          Your email address (for license management and opted-in communications)
        </li>
        <li className="mb-2">Your hashed machine identifier (for license validation)</li>
        <li className="mb-2">
          Subscription and payment records (maintained by LemonSqueezy)
        </li>
      </ul>

      <h2 className="text-xl sm:text-2xl font-montserrat font-semibold text-gray-900 mt-10 mb-4 tracking-tight">
        6. Your Rights and Choices
      </h2>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        6.1 General Rights (All Users)
      </h3>
      <ul className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4 ml-6 list-disc">
        <li className="mb-2">
          <strong>Opt out of promotional emails:</strong> You can unsubscribe from promotional
          communications at any time using the unsubscribe link in our emails or by contacting{" "}
          <a
            href="mailto:help@shhhtype.com"
            className="text-rose-600 hover:text-rose-700 underline"
          >
            help@shhhtype.com
          </a>
          .
        </li>
        <li className="mb-2">
          <strong>Choose local transcription:</strong> You can use ShhhType entirely offline by
          selecting local transcription mode &mdash; no data will be sent to any external service.
        </li>
        <li className="mb-2">
          <strong>Delete local data:</strong> You can delete your transcription history, dictionary,
          and settings at any time by removing the application data directory.
        </li>
        <li className="mb-2">
          <strong>Request data deletion:</strong> Contact{" "}
          <a
            href="mailto:help@shhhtype.com"
            className="text-rose-600 hover:text-rose-700 underline"
          >
            help@shhhtype.com
          </a>{" "}
          to request deletion of your email and license information from our systems.
        </li>
      </ul>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        6.2 European Economic Area (EEA) Residents &mdash; GDPR
      </h3>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        If you are located in the EEA, you have the following additional rights under the General
        Data Protection Regulation (GDPR):
      </p>
      <ul className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4 ml-6 list-disc">
        <li className="mb-2">
          <strong>Right of access:</strong> Request a copy of the personal data we hold about you.
        </li>
        <li className="mb-2">
          <strong>Right to rectification:</strong> Request correction of inaccurate personal data.
        </li>
        <li className="mb-2">
          <strong>Right to erasure:</strong> Request deletion of your personal data.
        </li>
        <li className="mb-2">
          <strong>Right to restriction:</strong> Request that we limit processing of your personal
          data.
        </li>
        <li className="mb-2">
          <strong>Right to data portability:</strong> Request your data in a structured,
          machine-readable format.
        </li>
        <li className="mb-2">
          <strong>Right to object:</strong> Object to processing of your personal data for certain
          purposes.
        </li>
        <li className="mb-2">
          <strong>Right to withdraw consent:</strong> Withdraw consent for promotional
          communications at any time.
        </li>
      </ul>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        Our legal basis for processing your data is:
      </p>
      <ul className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4 ml-6 list-disc">
        <li className="mb-2">
          <strong>Contract performance</strong> &mdash; for license management and service delivery.
        </li>
        <li className="mb-2">
          <strong>Legitimate interest</strong> &mdash; for fraud prevention and service improvement.
        </li>
        <li className="mb-2">
          <strong>Consent</strong> &mdash; for promotional communications (opt-in).
        </li>
      </ul>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        To exercise these rights, contact us at{" "}
        <a href="mailto:help@shhhtype.com" className="text-rose-600 hover:text-rose-700 underline">
          help@shhhtype.com
        </a>
        . We will respond within 30 days.
      </p>

      <h3 className="text-lg font-montserrat font-semibold text-gray-900 mt-6 mb-3">
        6.3 California Residents &mdash; CCPA
      </h3>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        If you are a California resident, you have the right to:
      </p>
      <ul className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4 ml-6 list-disc">
        <li className="mb-2">
          <strong>Know</strong> what personal information we collect and how it is used.
        </li>
        <li className="mb-2">
          <strong>Delete</strong> your personal information.
        </li>
        <li className="mb-2">
          <strong>Opt out</strong> of the sale of personal information &mdash; we do not sell your
          personal information.
        </li>
        <li className="mb-2">
          <strong>Non-discrimination</strong> &mdash; we will not discriminate against you for
          exercising your CCPA rights.
        </li>
      </ul>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        To exercise these rights, contact us at{" "}
        <a href="mailto:help@shhhtype.com" className="text-rose-600 hover:text-rose-700 underline">
          help@shhhtype.com
        </a>
        .
      </p>

      <h2 className="text-xl sm:text-2xl font-montserrat font-semibold text-gray-900 mt-10 mb-4 tracking-tight">
        7. International Data Transfers
      </h2>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        If you are located outside the United States, please be aware that your information (email
        address, hashed machine identifier) may be transferred to and processed in the United
        States, where Genesis 1 Technologies, LLC is located. By using the App, you consent to this
        transfer.
      </p>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        When audio data is sent to Groq for cloud transcription, it is processed on Groq&apos;s
        infrastructure. Please refer to Groq&apos;s privacy policy for information about their data
        processing locations.
      </p>

      <h2 className="text-xl sm:text-2xl font-montserrat font-semibold text-gray-900 mt-10 mb-4 tracking-tight">
        8. Children&apos;s Privacy
      </h2>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        ShhhType is a general-purpose productivity tool. We do not knowingly collect personal
        information from children under the age of 13. If we become aware that a child under 13 has
        provided us with personal information, we will take steps to delete such information. If you
        believe a child has provided us with personal information, please contact us at{" "}
        <a href="mailto:help@shhhtype.com" className="text-rose-600 hover:text-rose-700 underline">
          help@shhhtype.com
        </a>
        .
      </p>

      <h2 className="text-xl sm:text-2xl font-montserrat font-semibold text-gray-900 mt-10 mb-4 tracking-tight">
        9. Data Retention
      </h2>
      <ul className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4 ml-6 list-disc">
        <li className="mb-2">
          <strong>Email address and license data:</strong> Retained for as long as your subscription
          is active, plus 90 days after cancellation for account recovery purposes.
        </li>
        <li className="mb-2">
          <strong>Audio data:</strong> Not retained &mdash; processed in real time and discarded
          immediately.
        </li>
        <li className="mb-2">
          <strong>Local transcription history:</strong> Retained on your device until you delete it.
        </li>
        <li className="mb-2">
          <strong>Support correspondence:</strong> Retained for up to 2 years for quality and
          reference purposes.
        </li>
      </ul>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        After the retention period, data is permanently deleted from our systems.
      </p>

      <h2 className="text-xl sm:text-2xl font-montserrat font-semibold text-gray-900 mt-10 mb-4 tracking-tight">
        10. Changes to This Privacy Policy
      </h2>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        We may update this Privacy Policy from time to time. We will notify you of material changes
        by:
      </p>
      <ul className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4 ml-6 list-disc">
        <li className="mb-2">Posting the updated policy within the App;</li>
        <li className="mb-2">
          Posting the updated policy on our website at{" "}
          <a
            href="https://shhhtype.com"
            className="text-rose-600 hover:text-rose-700 underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            https://shhhtype.com
          </a>
          ;
        </li>
        <li className="mb-2">
          Sending an email notification for significant changes (if you have provided your email).
        </li>
      </ul>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        Your continued use of the App after the effective date of an updated Privacy Policy
        constitutes your acceptance of the changes.
      </p>

      <h2 className="text-xl sm:text-2xl font-montserrat font-semibold text-gray-900 mt-10 mb-4 tracking-tight">
        11. Contact Us
      </h2>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        If you have questions, concerns, or requests regarding this Privacy Policy or your personal
        data, please contact us at:
      </p>
      <p className="text-sm sm:text-base text-gray-600 font-montserrat leading-relaxed mb-4">
        <strong>Genesis 1 Technologies, LLC</strong>
        <br />
        Email:{" "}
        <a href="mailto:help@shhhtype.com" className="text-rose-600 hover:text-rose-700 underline">
          help@shhhtype.com
        </a>
        <br />
        Website:{" "}
        <a
          href="https://shhhtype.com"
          className="text-rose-600 hover:text-rose-700 underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          https://shhhtype.com
        </a>
      </p>
    </div>
  );
}
