import { ArrowRight, ChevronDown, Command, Mic, Zap, Sparkles } from "lucide-react";
import Image from "next/image";

const SIGNUP_URL = "/signup";

export function Hero() {
  return (
    <div className="bg-white rounded-2xl sm:rounded-[2rem] md:rounded-[3rem] p-6 sm:p-10 md:p-14 lg:p-16 shadow-sm border border-gray-100 relative overflow-hidden group transition-shadow duration-700">
      {/* Subtle Background Grid */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] pointer-events-none"></div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-16 items-center relative z-10">
        {/* Left Content */}
        <div className="lg:col-span-7 flex flex-col justify-center min-w-0">
          {/* Status Badge */}
          <div className="animate-fade-up delay-100 w-fit inline-flex items-center gap-2.5 bg-white/80 backdrop-blur border border-gray-200 text-gray-600 px-4 py-1.5 rounded-full text-xs font-montserrat font-semibold mb-5 sm:mb-8 shadow-sm hover:border-rose-200 transition-colors">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
            </span>
            VOICE-TO-CONTENT
          </div>

          {/* Headline */}
          <h1 className="animate-fade-up delay-200 text-[2.25rem] sm:text-5xl md:text-7xl lg:text-[5.5rem] leading-[1.05] sm:leading-[0.95] tracking-tight mb-5 sm:mb-8 text-gray-900 font-medium">
            Speak it.
            <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-rose-500 to-orange-500">Publish it.</span>
          </h1>

          {/* Description */}
          <p className="animate-fade-up delay-300 text-sm sm:text-lg md:text-xl text-gray-500 leading-relaxed max-w-lg mb-8 sm:mb-10 font-montserrat font-medium">
            What used to take 30 minutes now takes 60 seconds. Speak your ideas, say <span className="text-green-600 font-mono font-bold">/linkedin</span>, and get a formatted post with bold text, hooks, and hashtags. Your voice, structured by AI — not generated by it.
          </p>

          {/* Buttons */}
          <div className="animate-fade-up delay-500 flex flex-wrap gap-3 sm:gap-4 items-center">
            <a
              href={SIGNUP_URL}
              className="bg-gray-900 text-white pl-6 sm:pl-8 pr-5 sm:pr-6 py-3.5 sm:py-4 rounded-full text-sm sm:text-base hover:bg-rose-600 hover:shadow-lg hover:shadow-rose-600/20 transition-all duration-300 flex items-center gap-2 sm:gap-3 font-montserrat font-medium group/btn min-h-[44px]"
            >
              Start Free Trial
              <div className="bg-white/20 rounded-full p-1 group-hover/btn:bg-white/30 transition-colors">
                <ArrowRight className="w-3 h-3 group-hover/btn:translate-x-0.5 transition-transform" />
              </div>
            </a>
            <a
              href="#features"
              className="text-gray-600 px-4 sm:px-6 py-3.5 sm:py-4 rounded-full text-sm sm:text-base hover:text-gray-900 transition-all duration-300 font-montserrat font-medium flex items-center gap-2 group/link min-h-[44px]"
            >
              <ChevronDown className="w-4 h-4 text-gray-400 group-hover/link:text-gray-900 transition-colors" />
              See Features
            </a>
          </div>
        </div>

        {/* Right Visual: 4-Step Flow */}
        <div className="lg:col-span-5 relative h-auto lg:h-[600px] w-full min-w-0 overflow-hidden animate-slide-in delay-300">
          {/* Decorative offset background - only show at lg when grid is 2-col */}
          <div className="absolute top-10 right-10 w-full h-full bg-orange-100/50 rounded-[2rem] -rotate-3 z-0 hidden lg:block"></div>

          {/* Main Container */}
          <div className="relative h-full w-full bg-gradient-to-br from-orange-50/80 via-white to-rose-50/80 rounded-2xl sm:rounded-[2rem] overflow-hidden shadow-2xl border border-orange-100/50 z-10 flex flex-col items-center justify-center p-4 sm:p-8 gap-4">
            {/* Background pattern */}
            <div className="absolute inset-0 bg-[radial-gradient(#f43f5e_1px,transparent_1px)] [background-size:20px_20px] opacity-[0.05]"></div>

            {/* Floating Badge Top Right */}
            <div className="absolute top-16 right-8 z-30 animate-fade-up delay-500 hidden md:block">
              <div className="bg-orange-100/90 backdrop-blur-md p-4 rounded-2xl shadow-xl border border-orange-200/50 rotate-12 hover:rotate-0 transition-transform duration-500 cursor-pointer">
                <Mic className="w-7 h-7 text-orange-600" />
              </div>
            </div>

            {/* Floating Badge Bottom Left */}
            <div className="absolute bottom-16 left-8 z-30 animate-fade-up delay-700 hidden md:block">
              <div className="bg-orange-100/90 backdrop-blur-md p-4 rounded-2xl shadow-xl border border-orange-200/50 -rotate-12 hover:rotate-0 transition-transform duration-500 cursor-pointer">
                <Sparkles className="w-7 h-7 text-orange-600" />
              </div>
            </div>

            {/* Step Cards */}
            <div className="relative z-20 w-full max-w-sm space-y-2.5 sm:space-y-3">
              {/* Step 1 */}
              <div className="flex items-center gap-3 bg-white rounded-2xl p-3.5 sm:p-4 shadow-md border border-gray-100 hover:shadow-lg transition-shadow overflow-hidden">
                <div className="w-10 h-10 sm:w-11 sm:h-11 rounded-xl bg-gradient-to-br from-rose-500 to-orange-500 flex items-center justify-center text-white flex-shrink-0">
                  <Command className="w-5 h-5" />
                </div>
                <div className="min-w-0">
                  <p className="text-sm font-montserrat font-bold text-gray-900 truncate">Hold your hotkey</p>
                  <p className="text-xs text-gray-500 font-montserrat mt-0.5 truncate">One shortcut from any app</p>
                </div>
              </div>
              {/* Step 2 */}
              <div className="flex items-center gap-3 bg-white rounded-2xl p-3.5 sm:p-4 shadow-md border border-gray-100 hover:shadow-lg transition-shadow overflow-hidden">
                <div className="w-10 h-10 sm:w-11 sm:h-11 rounded-xl bg-gradient-to-br from-rose-500 to-orange-500 flex items-center justify-center text-white flex-shrink-0">
                  <Mic className="w-5 h-5" />
                </div>
                <div className="min-w-0">
                  <p className="text-sm font-montserrat font-bold text-gray-900 truncate">Speak for 30 seconds</p>
                  <p className="text-xs text-gray-500 font-montserrat mt-0.5 truncate">Say &quot;/linkedin&quot; to trigger a skill</p>
                </div>
              </div>
              {/* Step 3 */}
              <div className="flex items-center gap-3 bg-white rounded-2xl p-3.5 sm:p-4 shadow-md border border-gray-100 hover:shadow-lg transition-shadow overflow-hidden">
                <div className="w-10 h-10 sm:w-11 sm:h-11 rounded-xl bg-gradient-to-br from-rose-500 to-orange-500 flex items-center justify-center text-white flex-shrink-0">
                  <Zap className="w-5 h-5" />
                </div>
                <div className="min-w-0">
                  <p className="text-sm font-montserrat font-bold text-gray-900 truncate">AI structures your words</p>
                  <p className="text-xs text-gray-500 font-montserrat mt-0.5 truncate">Hook, bold text, hashtags — automatic</p>
                </div>
              </div>
              {/* Step 4 */}
              <div className="flex items-center gap-3 bg-white rounded-2xl p-3.5 sm:p-4 shadow-md border border-gray-100 hover:shadow-lg transition-shadow overflow-hidden">
                <div className="w-10 h-10 sm:w-11 sm:h-11 rounded-xl bg-gradient-to-br from-rose-500 to-orange-500 flex items-center justify-center text-white flex-shrink-0">
                  <Sparkles className="w-5 h-5" />
                </div>
                <div className="min-w-0">
                  <p className="text-sm font-montserrat font-bold text-gray-900 truncate">Publish</p>
                  <p className="text-xs text-gray-500 font-montserrat mt-0.5 truncate">60 seconds, start to finish</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
